# Generated by Django 5.0 on 2024-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokemonPredictor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='description',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='PokemonA_Type',
            field=models.CharField(default='Fire', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='PokemonB_Type',
            field=models.CharField(default='Water', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='prediction_result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
